### ISSUE TITLE
Is there a simple example available?

### ISSUE THREAD

**Issue by jarnoldv** [rochus-keller/BUSY#10]
Is there a simple BUSY.busy file available? Say having 1 C++ file generating an executable, just to get started? I don't even know where to start!

**Comment by rochus-keller** [comment]
Well, some day I will have to write tutorials or even a manual, but for now it's easier to answer questions.

Let's say you have a main.cpp with this content:

```
#include <iostream>
int main(int argc, char *argv[]) {
    std::cout << "Hello World!" << std::endl;
    return 0;
}
```

Here is the BUSY file which likely works on all platforms:

```
let hello ! : Executable {
    .sources += ./main.cpp
    if target_toolchain == `gcc {
        .lib_names += "stdc++"
        .ldflags += "-shared-libgcc"
    }
}
```

**Comment by rochus-keller** [comment]
can we close this?

**Comment by jarnoldv** [comment]
Yes, sorry! That sample worked fine.
