### ISSUE TITLE
Is it a build system or a project generator?

### ISSUE THREAD

**Issue by superchick** [rochus-keller/BUSY#14]
It advertised itself to be a build system. But it lacked basic features of a build system:

- No parallel builds: https://github.com/rochus-keller/BUSY/issues/8
- No dependencies check: https://github.com/rochus-keller/BUSY/issues/9

I suggest you better to reintroduce it as a project generator, e.g: like `premake`, `GENie`,...

You can keep the current build backend. It's still the default backend if no backend, e.g: `Ninja`, is specified.

**Comment by rochus-keller** [comment]
It's definitely a build system. It is able to build large C++ projects (such as LeanQt or LeanCreator) from green field to shared libraries and executables. The primary purpose of the basic system is to enable bootstrap builds with no other dependencies than a compiler and linker. If you need parallel and incremental builds, you can use the version integrated in LeanCreator. But it is no package manager and doesn't want to be one.

**Comment by superchick** [comment]
A build system needs to be able to handle dependencies. A package manager also has nothing to do with finding dependencies. This is the different between build systems and project generators. It's not for no reason I said BUSY is a project generator. It will be especially true when you added the Ninja backend to BUSY. Note: Meson generates Ninja, but it can check for dependencies. It's a build system. Premake5 can generate GNU Makefiles. But it has no ability to check for dependencies. It's only a project generator!

**Comment by superchick** [comment]
LeanCreator is a graphical application. How can it be applicable in CLI-only environment like servers?

**Comment by rochus-keller** [comment]
> A build system needs to be able to find dependencies.

That's your definition. Do make, qmake or GN find dependencies? No, they use what you give them. The same applies to BUSY, which is designed to be useful to build large software systems such as the ones mentioned, but also Chromium or Mono.

> LeanCreator is a graphical application.

So what? It's an IDE with an integrated build system. If you want to create a CLI version, you can take the source code and modify it accordingly. That's what open-source is about. I write tools first and foremost for my personal need; it's great if others can profit from it, but it's not the main motivation.

**Comment by superchick** [comment]
> That's your definition. Do make, qmake or GN find dependencies? No, they use what you give them.

No one call them build systems. They are builders.

**Comment by superchick** [comment]
See:

Project generator: https://github.com/bkaradzic/GENie

Build system: https://github.com/RudjiGames/build
