### ISSUE TITLE
Support parallel compilation

### ISSUE THREAD

**Issue by ghost** [rochus-keller/BUSY#15]
Related: #8

Can you extract the build engine from LeanCreator? LeanCreator is a graphical application that can't be used on a CLI only environment.

**Comment by rochus-keller** [comment]
That's unfortunately not feasible. I could in fact implement an alternative BUSY command line application based on e.g. C++11 (or even LeanQt Core) which supports multi-threading. But that would no longer support simple bootstrap builds, which is the primary goal of BUSY. I actually planned to implement a Ninja generator for the original BUSY command line application which then would support multi-threaded command line builds, but there was very little interest by the public during the last two years, and I myself don't need it.

What's your use case?

**Comment by ghost** [comment]
> That's unfortunately not feasible. I could in fact implement an alternative BUSY command line application based on e.g. C++11 (or even LeanQt Core) which supports multi-threading. But that would no longer support simple bootstrap builds, which is the primary goal of BUSY. I actually planned to implement a Ninja generator for the original BUSY command line application which then would support multi-threaded command line builds, but there was very little interest by the public during the last two years, and I myself don't need it.

The build engine of LeanCreator will be extracted into a CLI only program named leanbuild so it can be run on a CLI only environment. I don't ask you to integrate it into BUSY's source code. It will remain an external program. It will not much different from Ninja.

> What's your use case?

I want to switch from Premake5. I'm currently using the gmake2 generator of Premake5.

**Comment by rochus-keller** [comment]
> The build engine of LeanCreator will be extracted into a CLI only program named leanbuild 

Well, you can try to implement it. This would essentially be my envisioned LeanQt Core application; but I still would use the original BUSY implementation - as done in LeanCreator - since otherwise I had to reimplement the parser, validator and language model. I re-use a lot of features from the Lua 5.1 VM and BUSY directly supports Lua scripting.

> I want to switch from Premake5

What's wrong with Premake?

**Comment by ghost** [comment]
> What's wrong with Premake?

I'm unable to compile premake-core on illumos. I think BUSY will be more portable. I want to port my programs to exotic platforms like HaikuOS, too.

**Comment by rochus-keller** [comment]
Well, that's exactly what BUSY was made for; the trade-off is that it doesn't use more recent C or C++ versions or special OS features, thus e.g. not supporting multy-threading. Usually that's no issue if you bootstrap a system.

**Comment by rochus-keller** [comment]
BUSY now supports Ninja, so you can specify a build using BUSY and then just generate and run a Ninja build on as many cores as you have.
