### ISSUE TITLE
Problem with the usage of tmpnam in loslib.c

### ISSUE THREAD

**Issue by stefanos82** [rochus-keller/BUSY#3]
The following warning is thrown at the end of compilation procedure:

```c
gcc *.c -O2 -lm -o lua
/usr/bin/ld: /tmp/ccoL5y7d.o: in function `os_tmpname':
loslib.c:(.text+0x2a0): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
```

As far as I can see from official Lua website, since Lua 5.2 they offer an alternative to choose `mkstemp` if POSIX is available: https://www.lua.org/source/5.2/loslib.c.html

**Comment by rochus-keller** [comment]
Well, I don't think it's worth much effort; likely not the most "dangerous" aspect in our lives ;-)

**Comment by stefanos82** [comment]
If you like this erroneous behavior by the compilation procedure, no worries from me lol!

**Comment by rochus-keller** [comment]
There are still so many things to do that I just have to prioritize and ignore less important things.

**Comment by stefanos82** [comment]
Break them down to smaller pieces to make your life easier to complete or have them listed as bullet points so others could jump in to help, **if** they know how *and* have the knowledge to do so? :thinking:

**Comment by rochus-keller** [comment]
I prefer outlines over bullet points, see https://github.com/rochus-keller/crossline/

**Comment by stefanos82** [comment]
That would work too.
