### ISSUE TITLE
Clarification from README.md

### ISSUE THREAD

**Issue by stefanos82** [rochus-keller/BUSY#4]
Here we read

![image](https://user-images.githubusercontent.com/1777466/227344619-b7fb2c01-bc16-4744-b21e-bfb8cba4d14a.png)

`with parts in C++99`...did you mean `C99` or did you mean `C++98` here?

**Comment by rochus-keller** [comment]
Oops, should be 98.

**Comment by stefanos82** [comment]
Very well; when you fix the typo, let me know so I can close the ticket.

**Comment by rochus-keller** [comment]
I fixed it, but will commit and push it when there are some more fixes.

**Comment by stefanos82** [comment]
Very nice :+1:
