### ISSUE TITLE
How to specify make jobs?

### ISSUE THREAD

**Issue by ghost** [rochus-keller/BUSY#8]
It seems by default it uses only one make job. This caused the build speed to be extremely slow, especially for large C++ code base like LeanQt and LeanCreator. I have read README.md many times and unless I missed something I don't find anywhere it mentioned about make jobs or parallelization.

**Comment by rochus-keller** [comment]
The focus of the bare BUSY build system is on bootstrapping; adding threads increases complexity, but maybe I will do so in future.

But if you use LeanCreator, it uses all available cores by default, and it also uses the build-in C/C++ model to consider nested header modifications to decide what to build.

**Comment by ghost** [comment]
I don't know. I use Windows Task Manager and I confirm there is only one cc1plus process.

**Comment by rochus-keller** [comment]
Aparently you are using the command line version of BUSY, `lua build.lua xyz` and such.

If you want to use LeanCreator, there are a bunch of precompiled downloads: https://github.com/rochus-keller/LeanCreator/#precompiled-versions

Generating Ninja files from BUSY is still on my TODO list, but the build system integrated with LeanCreator is at least as fast and doesn't require a separate tool.
